
on:
    push:

# can filter jobs using GITHUB_ACTOR=nektos/act

env:
    DOCKER_BUILDKIT: 1

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                # only checkout on github
                if: env.GITHUB_ACTOR != "nektos/act"
                uses: actions/checkout@v1
            -
                name: env
                run: |
                    env
                    git status
            -
                name: build image
                run: |
                    docker build -t test .
            
    