
on:
    # github requires the events to be ones it knows about
    # this one is basically some form of "custom external webhook"
    repository_dispatch:
        types: [local]

env:
    DOCKER_BUILDKIT: 1

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: build image
                run: |
                    docker build -t test .
            
    