
on:
    # github requires the events to be ones it knows about
    # this one is basically some form of "custom external webhook"
    repository_dispatch:
        types: [local]

env:
    DOCKER_BUILDKIT: 1

jobs:
    run:
        # looks like you can't do dependencies between workflows?
        #needs: build
        runs-on: ubuntu-latest
        steps:
            -
                name: run image
                run: |
                    docker rm -f testrun || true
                    docker run --name testrun --rm -it -P test
                    # TODO: raise an issue that the ctrl-c isn't passed on to container..
            
    